<<<<<<< HEAD
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Paneles;

import Negocio.Backend;
import Vista.*;
import javax.swing.JFrame;

/**
 *
 * @author luisv
 */
public class panelServicios extends javax.swing.JPanel {

    /**
     * Creates new form panelServicios
     */
    public panelServicios() {
        initComponents();
        Backend.ConsultaServicio(this.tServicios);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pBotonesServicio = new javax.swing.JPanel();
        btnContratServicio = new javax.swing.JButton();
        pEspacio1 = new javax.swing.JPanel();
        btnAddServicio = new javax.swing.JButton();
        btnEditServicio = new javax.swing.JButton();
        btnBorrarServicio = new javax.swing.JButton();
        pServicioEvt = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tServicioEvento = new javax.swing.JTable();
        pServicios = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tServicios = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        pBotonesServicio.setBackground(new java.awt.Color(42, 42, 42));
        pBotonesServicio.setForeground(new java.awt.Color(42, 42, 42));
        pBotonesServicio.setMinimumSize(new java.awt.Dimension(123, 35));
        pBotonesServicio.setLayout(new javax.swing.BoxLayout(pBotonesServicio, javax.swing.BoxLayout.LINE_AXIS));

        btnContratServicio.setBackground(new java.awt.Color(57, 105, 138));
        btnContratServicio.setText("Contrartar Servicio");
        btnContratServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContratServicioActionPerformed(evt);
            }
        });
        pBotonesServicio.add(btnContratServicio);

        pEspacio1.setBackground(new java.awt.Color(42, 42, 42));
        pEspacio1.setForeground(new java.awt.Color(42, 42, 42));
        pEspacio1.setPreferredSize(new java.awt.Dimension(472, 24));

        javax.swing.GroupLayout pEspacio1Layout = new javax.swing.GroupLayout(pEspacio1);
        pEspacio1.setLayout(pEspacio1Layout);
        pEspacio1Layout.setHorizontalGroup(
            pEspacio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 427, Short.MAX_VALUE)
        );
        pEspacio1Layout.setVerticalGroup(
            pEspacio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        pBotonesServicio.add(pEspacio1);

        btnAddServicio.setBackground(new java.awt.Color(100, 221, 23));
        btnAddServicio.setText("Agregar");
        btnAddServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddServicioActionPerformed(evt);
            }
        });
        pBotonesServicio.add(btnAddServicio);

        btnEditServicio.setBackground(new java.awt.Color(57, 105, 138));
        btnEditServicio.setText("Editar");
        btnEditServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditServicioActionPerformed(evt);
            }
        });
        pBotonesServicio.add(btnEditServicio);

        btnBorrarServicio.setBackground(new java.awt.Color(57, 105, 138));
        btnBorrarServicio.setText("Borrar");
        pBotonesServicio.add(btnBorrarServicio);

        add(pBotonesServicio, java.awt.BorderLayout.PAGE_START);

        pServicioEvt.setBackground(new java.awt.Color(42, 42, 42));
        pServicioEvt.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Servicios contratados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(250, 250, 250))); // NOI18N
        pServicioEvt.setLayout(new java.awt.BorderLayout());

        tServicioEvento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Evento", "Servicio", "Precio"
            }
        ));
        jScrollPane5.setViewportView(tServicioEvento);

        pServicioEvt.add(jScrollPane5, java.awt.BorderLayout.CENTER);

        add(pServicioEvt, java.awt.BorderLayout.CENTER);

        pServicios.setBackground(new java.awt.Color(42, 42, 42));
        pServicios.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Catalogo Servicios", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(250, 250, 250))); // NOI18N
        pServicios.setPreferredSize(new java.awt.Dimension(400, 448));
        pServicios.setLayout(new java.awt.BorderLayout());

        tServicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre Servicio", "Precio"
            }
        ));
        jScrollPane6.setViewportView(tServicios);

        pServicios.add(jScrollPane6, java.awt.BorderLayout.CENTER);

        add(pServicios, java.awt.BorderLayout.LINE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void btnContratServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContratServicioActionPerformed
        // TODO add your handling code here:
        Dialog_ContratarServicio v = new Dialog_ContratarServicio((JFrame) this.getRootPane().getParent(), true);
        v.setVisible(true);
    }//GEN-LAST:event_btnContratServicioActionPerformed

    private void btnAddServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddServicioActionPerformed
        // TODO add your handling code here:
        Dialog_Servicio ds = new Dialog_Servicio((JFrame) this.getRootPane().getParent(), true);
        ds.setVisible(true);
    }//GEN-LAST:event_btnAddServicioActionPerformed

    private void btnEditServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditServicioActionPerformed
        // TODO add your handling code here:
        Dialog_Servicio v = new Dialog_Servicio((JFrame) this.getRootPane().getParent(), true);
        v.setVisible(true);
    }//GEN-LAST:event_btnEditServicioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddServicio;
    private javax.swing.JButton btnBorrarServicio;
    private javax.swing.JButton btnContratServicio;
    private javax.swing.JButton btnEditServicio;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JPanel pBotonesServicio;
    private javax.swing.JPanel pEspacio1;
    private javax.swing.JPanel pServicioEvt;
    private javax.swing.JPanel pServicios;
    private javax.swing.JTable tServicioEvento;
    private javax.swing.JTable tServicios;
    // End of variables declaration//GEN-END:variables
}
=======
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Paneles;

import Modelo.ModelEvento_Servicio;
import Negocio.Backend;
import Vista.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author luisv
 */
public class panelServicios extends javax.swing.JPanel {
    
    private ModelEvento_Servicio evtServicio;
    public static int ID;

    /**
     * Creates new form panelServicios
     */
    public panelServicios() {
        initComponents();
        Backend.ConsultaServicio(this.tServicios);
        evtServicio = new ModelEvento_Servicio(tServicioEvento);
        evtServicio.getContratados();
        this.btnEditServicio.setEnabled(false);
        ocultar_columna();
        metodo();
    }
    
    private void ocultar_columna(){
        this.tServicios.getColumnModel().getColumn(0).setMaxWidth(0);
        this.tServicios.getColumnModel().getColumn(0).setMinWidth(0);
        this.tServicios.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
        this.tServicios.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pBotonesServicio = new javax.swing.JPanel();
        btnContratServicio = new javax.swing.JButton();
        pEspacio1 = new javax.swing.JPanel();
        btnAddServicio = new javax.swing.JButton();
        btnEditServicio = new javax.swing.JButton();
        btnBorrarServicio = new javax.swing.JButton();
        pServicioEvt = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tServicioEvento = new javax.swing.JTable();
        pServicios = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tServicios = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        pBotonesServicio.setBackground(new java.awt.Color(42, 42, 42));
        pBotonesServicio.setForeground(new java.awt.Color(42, 42, 42));
        pBotonesServicio.setMinimumSize(new java.awt.Dimension(123, 35));
        pBotonesServicio.setLayout(new javax.swing.BoxLayout(pBotonesServicio, javax.swing.BoxLayout.LINE_AXIS));

        btnContratServicio.setBackground(new java.awt.Color(57, 105, 138));
        btnContratServicio.setText("Contrartar Servicio");
        btnContratServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContratServicioActionPerformed(evt);
            }
        });
        pBotonesServicio.add(btnContratServicio);

        pEspacio1.setBackground(new java.awt.Color(42, 42, 42));
        pEspacio1.setForeground(new java.awt.Color(42, 42, 42));
        pEspacio1.setPreferredSize(new java.awt.Dimension(472, 24));

        javax.swing.GroupLayout pEspacio1Layout = new javax.swing.GroupLayout(pEspacio1);
        pEspacio1.setLayout(pEspacio1Layout);
        pEspacio1Layout.setHorizontalGroup(
            pEspacio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 427, Short.MAX_VALUE)
        );
        pEspacio1Layout.setVerticalGroup(
            pEspacio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        pBotonesServicio.add(pEspacio1);

        btnAddServicio.setBackground(new java.awt.Color(100, 221, 23));
        btnAddServicio.setText("Agregar");
        btnAddServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddServicioActionPerformed(evt);
            }
        });
        pBotonesServicio.add(btnAddServicio);

        btnEditServicio.setBackground(new java.awt.Color(57, 105, 138));
        btnEditServicio.setText("Editar");
        btnEditServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditServicioActionPerformed(evt);
            }
        });
        pBotonesServicio.add(btnEditServicio);

        btnBorrarServicio.setBackground(new java.awt.Color(57, 105, 138));
        btnBorrarServicio.setText("Borrar");
        pBotonesServicio.add(btnBorrarServicio);

        add(pBotonesServicio, java.awt.BorderLayout.PAGE_START);

        pServicioEvt.setBackground(new java.awt.Color(42, 42, 42));
        pServicioEvt.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Servicios contratados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(250, 250, 250))); // NOI18N
        pServicioEvt.setLayout(new java.awt.BorderLayout());

        tServicioEvento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Evento", "Servicio", "Precio"
            }
        ));
        tServicioEvento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tServicioEventoMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tServicioEvento);

        pServicioEvt.add(jScrollPane5, java.awt.BorderLayout.CENTER);

        add(pServicioEvt, java.awt.BorderLayout.CENTER);

        pServicios.setBackground(new java.awt.Color(42, 42, 42));
        pServicios.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Catalogo Servicios", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(250, 250, 250))); // NOI18N
        pServicios.setPreferredSize(new java.awt.Dimension(400, 448));
        pServicios.setLayout(new java.awt.BorderLayout());

        tServicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre Servicio", "Precio"
            }
        ));
        tServicios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tServiciosMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tServicios);

        pServicios.add(jScrollPane6, java.awt.BorderLayout.CENTER);

        add(pServicios, java.awt.BorderLayout.LINE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void btnContratServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContratServicioActionPerformed
        // TODO add your handling code here:
        Dialog_ContratarServicio v = new Dialog_ContratarServicio((JFrame) this.getRootPane().getParent(), true);
        v.setVisible(true);
        evtServicio = new ModelEvento_Servicio(tServicioEvento);
        evtServicio.getContratados();
    }//GEN-LAST:event_btnContratServicioActionPerformed

    private void btnAddServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddServicioActionPerformed
        // TODO add your handling code here:
        Dialog_Servicio.var = false;
        Dialog_Servicio ds = new Dialog_Servicio((JFrame) this.getRootPane().getParent(), true);       
        this.btnEditServicio.setEnabled(false);
        ds.setVisible(true);
    }//GEN-LAST:event_btnAddServicioActionPerformed

    private void btnEditServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditServicioActionPerformed
        // TODO add your handling code here:
        Dialog_Servicio.var = true;
        Dialog_Servicio v = new Dialog_Servicio((JFrame) this.getRootPane().getParent(), true);
        v.setVisible(true);
        v.setID = ID;
        this.btnEditServicio.setEnabled(false);
        
    }//GEN-LAST:event_btnEditServicioActionPerformed

    private void tServiciosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tServiciosMouseClicked
        // TODO add your handling code here:
        if (tServicios.getSelectedRow()<0) return;
        System.out.println("asdf");
    }//GEN-LAST:event_tServiciosMouseClicked

    private void tServicioEventoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tServicioEventoMouseClicked
        // TODO add your handling code here:
        if (tServicioEvento.getSelectedRow()<0) return;
        System.out.println("qwerty");
    }//GEN-LAST:event_tServicioEventoMouseClicked

         private int metodo(){
     this.tServicios.addMouseListener(new MouseAdapter() 
   {

      @Override
      public void mousePressed(MouseEvent e) 
      {
         int fila = tServicios.rowAtPoint(e.getPoint());
         int columna = tServicios.columnAtPoint(e.getPoint());
         if ((fila > -1) && (columna > -1))
            btnEditServicio.setEnabled(true);
            int idd = (int)(tServicios.getValueAt(fila, 0));
            ID = idd;
      }
   });
     
     return ID;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddServicio;
    private javax.swing.JButton btnBorrarServicio;
    private javax.swing.JButton btnContratServicio;
    private javax.swing.JButton btnEditServicio;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JPanel pBotonesServicio;
    private javax.swing.JPanel pEspacio1;
    private javax.swing.JPanel pServicioEvt;
    private javax.swing.JPanel pServicios;
    private javax.swing.JTable tServicioEvento;
    private javax.swing.JTable tServicios;
    // End of variables declaration//GEN-END:variables
}
>>>>>>> 16ae818084db68c58647f11b921736d836ca68c4
