/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista.Paneles;

import Vista.*;
import javax.swing.JFrame;

/**
 *
 * @author luisv
 */
public class panelCatalogo extends javax.swing.JPanel {

    /** Creates new form panelCatalogo */
    public panelCatalogo() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupRegistrar = new javax.swing.JPopupMenu();
        miCliente = new javax.swing.JMenuItem();
        miSalon = new javax.swing.JMenuItem();
        miEntidad = new javax.swing.JMenuItem();
        miVtaBoleto = new javax.swing.JMenuItem();
        miEmpresaM = new javax.swing.JMenuItem();
        miSupervisor = new javax.swing.JMenuItem();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaRegistrar = new javax.swing.JTable();
        pButtonsTablas = new javax.swing.JPanel();
        btnAddRegistro = new javax.swing.JButton();
        panelEspacio2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();

        miCliente.setText("Cliente");
        miCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miClienteActionPerformed(evt);
            }
        });
        popupRegistrar.add(miCliente);

        miSalon.setText("Salón");
        miSalon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSalonActionPerformed(evt);
            }
        });
        popupRegistrar.add(miSalon);

        miEntidad.setText("Entidad Cliente");
        miEntidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEntidadActionPerformed(evt);
            }
        });
        popupRegistrar.add(miEntidad);

        miVtaBoleto.setText("Venta Boletos");
        miVtaBoleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miVtaBoletoActionPerformed(evt);
            }
        });
        popupRegistrar.add(miVtaBoleto);

        miEmpresaM.setText("Empresa de Mantenimiento");
        miEmpresaM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEmpresaMActionPerformed(evt);
            }
        });
        popupRegistrar.add(miEmpresaM);

        miSupervisor.setText("Supervisor");
        miSupervisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSupervisorActionPerformed(evt);
            }
        });
        popupRegistrar.add(miSupervisor);

        setLayout(new java.awt.BorderLayout());

        tablaRegistrar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaRegistrar);

        add(jScrollPane2, java.awt.BorderLayout.CENTER);

        pButtonsTablas.setBackground(new java.awt.Color(42, 42, 42));
        pButtonsTablas.setLayout(new javax.swing.BoxLayout(pButtonsTablas, javax.swing.BoxLayout.LINE_AXIS));

        btnAddRegistro.setBackground(new java.awt.Color(100, 221, 23));
        btnAddRegistro.setText("Agregar..");
        btnAddRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAddRegistroMousePressed(evt);
            }
        });
        pButtonsTablas.add(btnAddRegistro);

        panelEspacio2.setBackground(new java.awt.Color(42, 42, 42));
        panelEspacio2.setMinimumSize(new java.awt.Dimension(10, 100));
        panelEspacio2.setPreferredSize(new java.awt.Dimension(10, 24));

        javax.swing.GroupLayout panelEspacio2Layout = new javax.swing.GroupLayout(panelEspacio2);
        panelEspacio2.setLayout(panelEspacio2Layout);
        panelEspacio2Layout.setHorizontalGroup(
            panelEspacio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );
        panelEspacio2Layout.setVerticalGroup(
            panelEspacio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        pButtonsTablas.add(panelEspacio2);

        jLabel1.setForeground(new java.awt.Color(220, 220, 220));
        jLabel1.setText("Mostrar: ");
        pButtonsTablas.add(jLabel1);

        jComboBox2.setBackground(new java.awt.Color(57, 105, 138));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.setMaximumSize(new java.awt.Dimension(300, 32767));
        jComboBox2.setPreferredSize(new java.awt.Dimension(300, 20));
        pButtonsTablas.add(jComboBox2);

        add(pButtonsTablas, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddRegistroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddRegistroMousePressed
        // TODO add your handling code here:
        popupRegistrar.show(evt.getComponent(),
            3, //PosicionX
            evt.getComponent().getY()+evt.getComponent().getHeight()-2); //PosicionY
    }//GEN-LAST:event_btnAddRegistroMousePressed

    private void miClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miClienteActionPerformed
        // TODO add your handling code here:
        Registrar_Cliente rc = new Registrar_Cliente((JFrame) this.getRootPane().getParent(), true);
        rc.setVisible(true);
    }//GEN-LAST:event_miClienteActionPerformed

    private void miSalonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSalonActionPerformed
        // TODO add your handling code here:
        Registrar_Salón rs = new Registrar_Salón((JFrame) this.getRootPane().getParent(), true);
        rs.setVisible(true);
    }//GEN-LAST:event_miSalonActionPerformed

    private void miEntidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miEntidadActionPerformed
        // TODO add your handling code here:
        Registrar_Entidad re = new Registrar_Entidad((JFrame) this.getRootPane().getParent(), true);
        re.setVisible(true);
    }//GEN-LAST:event_miEntidadActionPerformed

    private void miVtaBoletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miVtaBoletoActionPerformed
        // TODO add your handling code here:
        Registrar_Venta_Boleto rvb = new Registrar_Venta_Boleto((JFrame) this.getRootPane().getParent(), true);
        rvb.setVisible(true);
    }//GEN-LAST:event_miVtaBoletoActionPerformed

    private void miEmpresaMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miEmpresaMActionPerformed
        // TODO add your handling code here:
        Registrar_Entidad re = new Registrar_Entidad((JFrame) this.getRootPane().getParent(), true);
        re.setVisible(true);
    }//GEN-LAST:event_miEmpresaMActionPerformed

    private void miSupervisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSupervisorActionPerformed
        // TODO add your handling code here:
        Registrar_Supervisor rs = new Registrar_Supervisor((JFrame) this.getRootPane().getParent(), true);
        rs.setVisible(true);
    }//GEN-LAST:event_miSupervisorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddRegistro;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuItem miCliente;
    private javax.swing.JMenuItem miEmpresaM;
    private javax.swing.JMenuItem miEntidad;
    private javax.swing.JMenuItem miSalon;
    private javax.swing.JMenuItem miSupervisor;
    private javax.swing.JMenuItem miVtaBoleto;
    private javax.swing.JPanel pButtonsTablas;
    private javax.swing.JPanel panelEspacio2;
    private javax.swing.JPopupMenu popupRegistrar;
    private javax.swing.JTable tablaRegistrar;
    // End of variables declaration//GEN-END:variables

}
