/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Paneles;

import Vista.*;
import javax.swing.JFrame;

/**
 *
 * @author luisv
 */
public class panelMantenimiento extends javax.swing.JPanel {

    /**
     * Creates new form panelMantenimiento
     */
    public panelMantenimiento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        pButtonsMant = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Salon", "Empresa", "Supervisor", "Tipo Mantenimiento", "Costo"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        add(jScrollPane4, java.awt.BorderLayout.CENTER);

        pButtonsMant.setBackground(new java.awt.Color(42, 42, 42));
        pButtonsMant.setLayout(new javax.swing.BoxLayout(pButtonsMant, javax.swing.BoxLayout.LINE_AXIS));

        jButton9.setBackground(new java.awt.Color(100, 221, 23));
        jButton9.setText("Agregar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        pButtonsMant.add(jButton9);

        jPanel7.setBackground(new java.awt.Color(42, 42, 42));
        jPanel7.setPreferredSize(new java.awt.Dimension(100, 24));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 561, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        pButtonsMant.add(jPanel7);

        jButton10.setBackground(new java.awt.Color(57, 105, 138));
        jButton10.setText("Editar");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        pButtonsMant.add(jButton10);

        jButton11.setBackground(new java.awt.Color(57, 105, 138));
        jButton11.setText("Borrar");
        pButtonsMant.add(jButton11);

        add(pButtonsMant, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        DialogMantenimiento v = new DialogMantenimiento((JFrame) this.getRootPane().getParent(), true);
        v.setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        DialogMantenimiento v = new DialogMantenimiento((JFrame) this.getRootPane().getParent(), true);
        v.setVisible(true);
    }//GEN-LAST:event_jButton10ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable4;
    private javax.swing.JPanel pButtonsMant;
    // End of variables declaration//GEN-END:variables
}
