/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.ModelEvento;
import Modelo.ModelVentaBoleto;
import Modelo.POJO.Evento;
import Modelo.POJO.VentaBoleto;
import java.util.Date;

/**
 *
 * @author fernando
 */
public class Dialog_VentaBoleto extends javax.swing.JDialog {
    
    private ModelEvento evento;
    private ModelVentaBoleto venta;

    /**
     * Creates new form Registar_Venta_Boleto
     */
    public Dialog_VentaBoleto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        evento = new ModelEvento(tEventos);
        evento.cargarParaVenta();
        venta = new ModelVentaBoleto();
    }
    
    private Evento getEvento(){
        return evento.getAt(tEventos.getSelectedRow());
    }
    
    private VentaBoleto getCampos(){
        VentaBoleto v = new VentaBoleto();
        v.setEvento(getEvento());
        v.setCedula(txtCedula.getText());
        v.setCantidadBoletos((Integer) spCantidad.getValue());
        v.setFecha(new Date());
        return v;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pInferior = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        btnOK = new javax.swing.JButton();
        pSuperior = new javax.swing.JPanel();
        pTop = new javax.swing.JPanel();
        pDatosGenerales = new javax.swing.JPanel();
        lblNombreCliente = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        lblPrecio = new javax.swing.JLabel();
        lblBoletosDisp = new javax.swing.JLabel();
        txtBoletosDisponibles = new javax.swing.JTextField();
        spCantidad = new javax.swing.JSpinner();
        pCenter = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tEventos = new javax.swing.JTable();
        lblTotalPagar = new javax.swing.JLabel();
        txtTotalPagar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(42, 42, 42));
        setResizable(false);

        pInferior.setBackground(new java.awt.Color(57, 60, 76));
        pInferior.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnCancelar.setFont(new java.awt.Font("HP Simplified", 0, 18)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setPreferredSize(new java.awt.Dimension(100, 40));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        pInferior.add(btnCancelar);

        btnOK.setBackground(new java.awt.Color(100, 221, 23));
        btnOK.setFont(new java.awt.Font("HP Simplified", 0, 18)); // NOI18N
        btnOK.setText("OK");
        btnOK.setPreferredSize(new java.awt.Dimension(100, 40));
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });
        pInferior.add(btnOK);

        getContentPane().add(pInferior, java.awt.BorderLayout.PAGE_END);

        pSuperior.setLayout(new java.awt.BorderLayout());

        pTop.setBackground(new java.awt.Color(42, 42, 42));
        pTop.setPreferredSize(new java.awt.Dimension(695, 200));
        pTop.setLayout(new javax.swing.BoxLayout(pTop, javax.swing.BoxLayout.LINE_AXIS));

        pDatosGenerales.setBackground(new java.awt.Color(57, 60, 76));
        pDatosGenerales.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Generales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(250, 250, 250))); // NOI18N
        pDatosGenerales.setForeground(new java.awt.Color(255, 255, 255));
        pDatosGenerales.setMaximumSize(new java.awt.Dimension(32767, 200));
        pDatosGenerales.setPreferredSize(new java.awt.Dimension(400, 200));

        lblNombreCliente.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        lblNombreCliente.setForeground(new java.awt.Color(207, 207, 207));
        lblNombreCliente.setText("Número de Cédula");

        lblPrecio.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        lblPrecio.setForeground(new java.awt.Color(207, 207, 207));
        lblPrecio.setText("Cantidad de Boletos");

        lblBoletosDisp.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        lblBoletosDisp.setForeground(new java.awt.Color(207, 207, 207));
        lblBoletosDisp.setText("Boletos Disponibles");

        txtBoletosDisponibles.setEditable(false);

        spCantidad.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        spCantidad.setModel(new javax.swing.SpinnerNumberModel(1, 1, 20, 1));

        javax.swing.GroupLayout pDatosGeneralesLayout = new javax.swing.GroupLayout(pDatosGenerales);
        pDatosGenerales.setLayout(pDatosGeneralesLayout);
        pDatosGeneralesLayout.setHorizontalGroup(
            pDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDatosGeneralesLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(pDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pDatosGeneralesLayout.createSequentialGroup()
                        .addComponent(spCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pDatosGeneralesLayout.createSequentialGroup()
                        .addGroup(pDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreCliente)
                            .addComponent(lblPrecio)
                            .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 45, Short.MAX_VALUE)
                        .addGroup(pDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBoletosDisp)
                            .addComponent(txtBoletosDisponibles, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE))
                        .addGap(68, 68, 68))))
        );
        pDatosGeneralesLayout.setVerticalGroup(
            pDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDatosGeneralesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pDatosGeneralesLayout.createSequentialGroup()
                        .addComponent(lblNombreCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pDatosGeneralesLayout.createSequentialGroup()
                        .addComponent(lblBoletosDisp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBoletosDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(lblPrecio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pTop.add(pDatosGenerales);

        pSuperior.add(pTop, java.awt.BorderLayout.PAGE_START);

        pCenter.setBackground(new java.awt.Color(42, 42, 42));

        tEventos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre del Salón", "Nombre del Evento", "Hora Inicio", "Hora Fin", "Cantidad de Personas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tEventos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tEventos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tEventosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tEventos);

        lblTotalPagar.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        lblTotalPagar.setForeground(new java.awt.Color(220, 220, 220));
        lblTotalPagar.setText("Total a Pagar:");

        javax.swing.GroupLayout pCenterLayout = new javax.swing.GroupLayout(pCenter);
        pCenter.setLayout(pCenterLayout);
        pCenterLayout.setHorizontalGroup(
            pCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCenterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(pCenterLayout.createSequentialGroup()
                        .addComponent(lblTotalPagar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotalPagar, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                        .addGap(481, 481, 481)))
                .addContainerGap())
        );
        pCenterLayout.setVerticalGroup(
            pCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCenterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(pCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalPagar)
                    .addComponent(txtTotalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pSuperior.add(pCenter, java.awt.BorderLayout.CENTER);

        getContentPane().add(pSuperior, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        // TODO add your handling code here:
        if (txtCedula.getText().equals("") || tEventos.getSelectedRow()<0) return;
        venta.addVenta(getCampos());
        this.dispose();
    }//GEN-LAST:event_btnOKActionPerformed

    private void tEventosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tEventosMouseClicked
        // TODO add your handling code here:
        int index = tEventos.getSelectedRow();
        if(index<0) return;
        txtTotalPagar.setText("$ "+(evento.getAt(index).getPrecioBoleto()*(int)spCantidad.getValue()));
        txtBoletosDisponibles.setText((evento.getAt(index).getCantidadPersonas())+"");
    }//GEN-LAST:event_tEventosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dialog_VentaBoleto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dialog_VentaBoleto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dialog_VentaBoleto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dialog_VentaBoleto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            Dialog_VentaBoleto dialog = new Dialog_VentaBoleto(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnOK;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBoletosDisp;
    private javax.swing.JLabel lblNombreCliente;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblTotalPagar;
    private javax.swing.JPanel pCenter;
    private javax.swing.JPanel pDatosGenerales;
    private javax.swing.JPanel pInferior;
    private javax.swing.JPanel pSuperior;
    private javax.swing.JPanel pTop;
    private javax.swing.JSpinner spCantidad;
    private javax.swing.JTable tEventos;
    private javax.swing.JTextField txtBoletosDisponibles;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtTotalPagar;
    // End of variables declaration//GEN-END:variables
}
