/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.ModelEmpresa;
import Modelo.ModelMantenimiento;
import Modelo.ModelSalon;
import Modelo.ModelSupervisor;
import Modelo.POJO.Mantenimiento;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author luisv
 */
public class Dialog_Mantenimiento extends javax.swing.JDialog {

    private ModelMantenimiento mant;
    private ModelEmpresa empresa;
    private ModelSupervisor supervisor;
    private ModelSalon salon;
    private Mantenimiento mantenimiento;
    private boolean edit;

    /**
     * Creates new form DialogMantenimiento
     */
    public Dialog_Mantenimiento(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        mant = new ModelMantenimiento();
        empresa = new ModelEmpresa();
        empresa.cargarLista(listEmpresa);
        supervisor = new ModelSupervisor();
        supervisor.cargarLista(listSupervisor);
        salon = new ModelSalon();
        salon.cargarComboBox(cbxSalon);
    }

    public void setEdit(boolean edit) {
        this.edit = edit;
    }

    public void setMantenimiento(Mantenimiento m) {
        this.mantenimiento = m;
    }

    public Mantenimiento getMantenimiento() {
        return mantenimiento;
    }

    private void getCampos() {
        Mantenimiento m = new Mantenimiento();
        m.setSalon(salon.getAt(cbxSalon.getSelectedIndex()));
        m.setEmpresa(empresa.getAt(listEmpresa.getSelectedIndex()));
        m.setSupervisor(supervisor.getAt(listSupervisor.getSelectedIndex()));
        m.setTipoMantenimiento(txtTipoMantenimiento.getText());
        m.setCosto((Float) spCosto.getValue());
        m.setFechaRegistro(new Date());
        setMantenimiento(m);
    }

    private void getEditCampos() {
        mantenimiento.setSalon(salon.getAt(cbxSalon.getSelectedIndex()));
        mantenimiento.setEmpresa(empresa.getAt(listEmpresa.getSelectedIndex()));
        mantenimiento.setSupervisor(supervisor.getAt(listSupervisor.getSelectedIndex()));
        mantenimiento.setTipoMantenimiento(txtTipoMantenimiento.getText());
        mantenimiento.setCosto((Float) spCosto.getValue());
        mantenimiento.setFechaRegistro(new Date());
    }

    public void setCampos() {
        cbxSalon.setSelectedItem(mantenimiento.getSalon().getNombre());
        txtEmpresa.setText(mantenimiento.getEmpresa().getNombre());
        txtSupervisor.setText(mantenimiento.getSupervisor().getNombre() + " " + mantenimiento.getSupervisor().getApellido());
        txtTipoMantenimiento.setText(mantenimiento.getTipoMantenimiento());
        spCosto.setValue(mantenimiento.getCosto());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbxSalon = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtEmpresa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSupervisor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTipoMantenimiento = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        spCosto = new javax.swing.JSpinner();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listSupervisor = new javax.swing.JList<>();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listEmpresa = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        btnOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(56, 60, 76));
        jPanel3.setPreferredSize(new java.awt.Dimension(400, 345));

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(250, 250, 250));
        jLabel1.setText("Salón");

        cbxSalon.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        cbxSalon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(250, 250, 250));
        jLabel2.setText("Empresa de Mantenimiento");

        txtEmpresa.setEditable(false);
        txtEmpresa.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        txtEmpresa.setText("Seleccione...");
        txtEmpresa.setPreferredSize(new java.awt.Dimension(84, 26));

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(250, 250, 250));
        jLabel3.setText("Supervisor");

        txtSupervisor.setEditable(false);
        txtSupervisor.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        txtSupervisor.setText("Seleccione..");
        txtSupervisor.setPreferredSize(new java.awt.Dimension(4, 26));

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(250, 250, 250));
        jLabel4.setText("Tipo de Mantenimiento");

        txtTipoMantenimiento.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        txtTipoMantenimiento.setPreferredSize(new java.awt.Dimension(4, 26));
        txtTipoMantenimiento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTipoMantenimientoKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(250, 250, 250));
        jLabel5.setText("Costo");

        spCosto.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        spCosto.setModel(new javax.swing.SpinnerNumberModel(1.0f, 1.0f, null, 5.0f));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtTipoMantenimiento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3)
                            .addComponent(txtSupervisor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1)
                            .addComponent(cbxSalon, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addComponent(txtEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                        .addGap(50, 50, 50))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(spCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxSalon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSupervisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTipoMantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel4.setPreferredSize(new java.awt.Dimension(250, 345));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel5.setBackground(new java.awt.Color(56, 60, 76));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Seleccione Supervisor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(250, 250, 250))); // NOI18N
        jPanel5.setLayout(new java.awt.BorderLayout());

        listSupervisor.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listSupervisor.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listSupervisor.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listSupervisorValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listSupervisor);

        jPanel5.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel6.setBackground(new java.awt.Color(56, 60, 76));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Seleccione Empresa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(250, 250, 250))); // NOI18N
        jPanel6.setPreferredSize(new java.awt.Dimension(300, 200));
        jPanel6.setLayout(new java.awt.BorderLayout());

        listEmpresa.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listEmpresa.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listEmpresa.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listEmpresaValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listEmpresa);

        jPanel6.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel6, java.awt.BorderLayout.PAGE_START);

        jPanel1.add(jPanel4, java.awt.BorderLayout.LINE_END);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(42, 42, 42));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnCancelar.setFont(new java.awt.Font("HP Simplified", 0, 18)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setPreferredSize(new java.awt.Dimension(100, 40));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancelar);

        btnOK.setBackground(new java.awt.Color(100, 221, 23));
        btnOK.setFont(new java.awt.Font("HP Simplified", 0, 18)); // NOI18N
        btnOK.setText("OK");
        btnOK.setPreferredSize(new java.awt.Dimension(100, 40));
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });
        jPanel2.add(btnOK);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        // TODO add your handling code here:
        if (txtTipoMantenimiento.getText().isEmpty() || listEmpresa.getSelectedIndex() < 0 || listSupervisor.getSelectedIndex() < 0) {
            JOptionPane.showMessageDialog(this, "No deje campos vacios");
            return;
        }
        if (edit) {
            mantenimiento = mant.getByID(mantenimiento.getIdMantenimiento());
            getEditCampos();
            mant.update(mantenimiento);
        } else {
            getCampos();
            mant.add(getMantenimiento());
            this.dispose();
        }

        this.dispose();
    }//GEN-LAST:event_btnOKActionPerformed

    private void txtTipoMantenimientoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTipoMantenimientoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if (Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();

            JOptionPane.showMessageDialog(null, "Ingrese solo letras");

        }
    }//GEN-LAST:event_txtTipoMantenimientoKeyTyped

    private void listEmpresaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listEmpresaValueChanged
        // TODO add your handling code here:
        txtEmpresa.setText(listEmpresa.getSelectedValue());
    }//GEN-LAST:event_listEmpresaValueChanged

    private void listSupervisorValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listSupervisorValueChanged
        // TODO add your handling code here:
        txtSupervisor.setText(listSupervisor.getSelectedValue());
    }//GEN-LAST:event_listSupervisorValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dialog_Mantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dialog_Mantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dialog_Mantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dialog_Mantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Dialog_Mantenimiento dialog = new Dialog_Mantenimiento(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnOK;
    private javax.swing.JComboBox<String> cbxSalon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listEmpresa;
    private javax.swing.JList<String> listSupervisor;
    private javax.swing.JSpinner spCosto;
    private javax.swing.JTextField txtEmpresa;
    private javax.swing.JTextField txtSupervisor;
    private javax.swing.JTextField txtTipoMantenimiento;
    // End of variables declaration//GEN-END:variables
}
