/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.IconFontUtil;
import Vista.Paneles.*;
import java.awt.*;
import java.io.InputStream;
import java.sql.Connection;
import javax.swing.*;
import javax.swing.plaf.basic.BasicMenuBarUI;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author luisv
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        cl = (CardLayout) panelCards.getLayout();
        cargarVistas();
        jMenuBar1.setUI(new BasicMenuBarUI());
        iconFont = new IconFontUtil();
        //setIconImage(new ImageIcon(getClass().getResource("/Vista/Imagenes/star.png")).getImage());
    }

    private void ColorButton(JButton btn) {
        /*Cambiar Color*/
        btnEventos.setBackground(new Color(57, 60, 76));
        btnTablas.setBackground(new Color(57, 60, 76));
        btnServicios.setBackground(new Color(57, 60, 76));
        btnMant.setBackground(new Color(57, 60, 76));
        btnUsuarios.setBackground(new Color(57, 60, 76));
        btnEventos.setForeground(Color.LIGHT_GRAY);
        btnTablas.setForeground(Color.LIGHT_GRAY);
        btnServicios.setForeground(Color.LIGHT_GRAY);
        btnMant.setForeground(Color.LIGHT_GRAY);
        btnUsuarios.setForeground(Color.LIGHT_GRAY);
        btn.setBackground(new Color(100, 221, 23));
        btn.setForeground(Color.BLACK);

        /*Cambiar Icono*/
        btnEventos.setIcon(iconFont.getEvt_G());
        btnTablas.setIcon(iconFont.getTablas_G());
        btnServicios.setIcon(iconFont.getServicio_G());
        btnMant.setIcon(iconFont.getMant_G());
        btnUsuarios.setIcon(iconFont.getUsuarios_G());
    }

    private void cargarVistas() {
        panelCards.add("evento", new panelEventos());
        panelCards.add("servicio", new panelServicios());
        panelCards.add("mantenimiento", new panelMantenimiento());
        panelCards.add("registrar", new panelCatalogo());
        panelCards.add("usuario", new panelUsuarios());

    }

// <editor-fold defaultstate="collapsed" desc="Generated Code NO BORRAR"> 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCards = new javax.swing.JPanel();
        panelNevegacion = new javax.swing.JPanel();
        btnEventos = new javax.swing.JButton();
        btnServicios = new javax.swing.JButton();
        btnMant = new javax.swing.JButton();
        btnTablas = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        statusBar = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mReportes = new javax.swing.JMenu();
        factCliente = new javax.swing.JMenuItem();
        EvtxCliente = new javax.swing.JMenuItem();
        MantSalon = new javax.swing.JMenuItem();
        servEvento = new javax.swing.JMenuItem();
        ventas = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Eventos");
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/star.png")).getImage());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        panelCards.setBackground(new java.awt.Color(42, 42, 42));
        panelCards.setToolTipText("");
        panelCards.setLayout(new java.awt.CardLayout());
        getContentPane().add(panelCards, java.awt.BorderLayout.CENTER);

        panelNevegacion.setBackground(new java.awt.Color(57, 60, 76));
        panelNevegacion.setMaximumSize(new java.awt.Dimension(32767, 50));
        panelNevegacion.setPreferredSize(new java.awt.Dimension(790, 50));
        panelNevegacion.setLayout(new javax.swing.BoxLayout(panelNevegacion, javax.swing.BoxLayout.LINE_AXIS));

        btnEventos.setBackground(new java.awt.Color(100, 221, 23));
        btnEventos.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        btnEventos.setIcon(new IconFontUtil().getEvt_B());
        btnEventos.setText("Eventos");
        btnEventos.setMaximumSize(new java.awt.Dimension(350, 50));
        btnEventos.setMinimumSize(new java.awt.Dimension(150, 50));
        btnEventos.setPreferredSize(new java.awt.Dimension(150, 50));
        btnEventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEventosActionPerformed(evt);
            }
        });
        panelNevegacion.add(btnEventos);

        btnServicios.setBackground(new java.awt.Color(57, 60, 76));
        btnServicios.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        btnServicios.setForeground(java.awt.Color.lightGray);
        btnServicios.setIcon(new IconFontUtil().getServicio_G());
        btnServicios.setText("Servicios");
        btnServicios.setMaximumSize(new java.awt.Dimension(350, 50));
        btnServicios.setMinimumSize(new java.awt.Dimension(150, 50));
        btnServicios.setPreferredSize(new java.awt.Dimension(150, 50));
        btnServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServiciosActionPerformed(evt);
            }
        });
        panelNevegacion.add(btnServicios);

        btnMant.setBackground(new java.awt.Color(57, 60, 76));
        btnMant.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        btnMant.setForeground(java.awt.Color.lightGray);
        btnMant.setIcon(new IconFontUtil().getMant_G());
        btnMant.setText("Mantenimientos");
        btnMant.setMaximumSize(new java.awt.Dimension(350, 50));
        btnMant.setMinimumSize(new java.awt.Dimension(150, 50));
        btnMant.setPreferredSize(new java.awt.Dimension(150, 50));
        btnMant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMantActionPerformed(evt);
            }
        });
        panelNevegacion.add(btnMant);

        btnTablas.setBackground(new java.awt.Color(57, 60, 76));
        btnTablas.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        btnTablas.setForeground(java.awt.Color.lightGray);
        btnTablas.setIcon(new IconFontUtil().getTablas_G());
        btnTablas.setText("Tablas");
        btnTablas.setMaximumSize(new java.awt.Dimension(350, 50));
        btnTablas.setMinimumSize(new java.awt.Dimension(150, 50));
        btnTablas.setPreferredSize(new java.awt.Dimension(150, 50));
        btnTablas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTablasActionPerformed(evt);
            }
        });
        panelNevegacion.add(btnTablas);

        btnUsuarios.setBackground(new java.awt.Color(57, 60, 76));
        btnUsuarios.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        btnUsuarios.setForeground(java.awt.Color.lightGray);
        btnUsuarios.setIcon(new IconFontUtil().getUsuarios_G());
        btnUsuarios.setText("Usuarios");
        btnUsuarios.setMaximumSize(new java.awt.Dimension(350, 50));
        btnUsuarios.setMinimumSize(new java.awt.Dimension(150, 50));
        btnUsuarios.setPreferredSize(new java.awt.Dimension(150, 50));
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });
        panelNevegacion.add(btnUsuarios);

        getContentPane().add(panelNevegacion, java.awt.BorderLayout.PAGE_START);

        statusBar.setBackground(new java.awt.Color(56, 60, 76));
        statusBar.setMaximumSize(new java.awt.Dimension(32767, 21));
        statusBar.setPreferredSize(new java.awt.Dimension(790, 21));

        javax.swing.GroupLayout statusBarLayout = new javax.swing.GroupLayout(statusBar);
        statusBar.setLayout(statusBarLayout);
        statusBarLayout.setHorizontalGroup(
            statusBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 818, Short.MAX_VALUE)
        );
        statusBarLayout.setVerticalGroup(
            statusBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        getContentPane().add(statusBar, java.awt.BorderLayout.PAGE_END);

        mReportes.setText("Reportes");

        factCliente.setText("Factura cliente");
        factCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                factClienteActionPerformed(evt);
            }
        });
        mReportes.add(factCliente);

        EvtxCliente.setText("Eventos por cliente");
        EvtxCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EvtxClienteActionPerformed(evt);
            }
        });
        mReportes.add(EvtxCliente);

        MantSalon.setText("Mantenimientos Salon");
        MantSalon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MantSalonActionPerformed(evt);
            }
        });
        mReportes.add(MantSalon);

        servEvento.setText("Servicios Eventos");
        servEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                servEventoActionPerformed(evt);
            }
        });
        mReportes.add(servEvento);

        ventas.setText("Ventas");
        ventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ventasActionPerformed(evt);
            }
        });
        mReportes.add(ventas);

        jMenuBar1.add(mReportes);

        jMenu4.setText("Ayuda");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
// </editor-fold>

    private void btnEventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEventosActionPerformed
        // TODO add your handling code here
        cl.show(panelCards, "evento");//Card Name = "evento"
        ColorButton(this.btnEventos);
        btnEventos.setIcon(iconFont.getEvt_B());
    }//GEN-LAST:event_btnEventosActionPerformed

    private void btnTablasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTablasActionPerformed
        // TODO add your handling code here:
        cl.show(panelCards, "registrar");
        ColorButton(this.btnTablas);
        btnTablas.setIcon(iconFont.getServicio_B());
        btnTablas.setIcon(iconFont.getTablas_B());
    }//GEN-LAST:event_btnTablasActionPerformed

    private void btnServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServiciosActionPerformed
        // TODO add your handling code here:
        cl.show(panelCards, "servicio");
        ColorButton(this.btnServicios);
        btnServicios.setIcon(iconFont.getServicio_B());
    }//GEN-LAST:event_btnServiciosActionPerformed

    private void btnMantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMantActionPerformed
        // TODO add your handling code here:
        cl.show(panelCards, "mantenimiento");
        ColorButton(this.btnMant);
        btnMant.setIcon(iconFont.getMant_B());
    }//GEN-LAST:event_btnMantActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        // TODO add your handling code here:
        cl.show(panelCards, "usuario");
        ColorButton(this.btnUsuarios);
        btnUsuarios.setIcon(iconFont.getUsuarios_B());
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        setExtendedState(MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    private void factClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_factClienteActionPerformed
        // TODO add your handling code here:
        InputStream reporte = this.getClass().getResourceAsStream("/Reportes/FactClientes.jasper");
        JasperPrint jasperPrint;

        Conexion con = new Conexion();
        Connection Conn = con.conectar();

        try {
            jasperPrint = JasperFillManager.fillReport(reporte, null, Conn);
            JasperViewer jv = new JasperViewer(jasperPrint, false);
            jv.setTitle("");
            jv.setVisible(true);
        } catch (JRException ex) {

        }
    }//GEN-LAST:event_factClienteActionPerformed

    private void EvtxClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EvtxClienteActionPerformed
        // TODO add your handling code here:
        InputStream reporte = this.getClass().getResourceAsStream("/Reportes/EventosxClientes.jasper");
        JasperPrint jasperPrint;

        Conexion con = new Conexion();
        Connection Conn = con.conectar();

        try {
            jasperPrint = JasperFillManager.fillReport(reporte, null, Conn);
            JasperViewer jv = new JasperViewer(jasperPrint, false);
            jv.setTitle("");
            jv.setVisible(true);
        } catch (JRException ex) {

        }
    }//GEN-LAST:event_EvtxClienteActionPerformed

    private void MantSalonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MantSalonActionPerformed
        // TODO add your handling code here:
        InputStream reporte = this.getClass().getResourceAsStream("/Reportes/Mantenimiento_saln.jasper");
        JasperPrint jasperPrint;

        Conexion con = new Conexion();
        Connection Conn = con.conectar();

        try {
            jasperPrint = JasperFillManager.fillReport(reporte, null, Conn);
            JasperViewer jv = new JasperViewer(jasperPrint, false);
            jv.setTitle("");
            jv.setVisible(true);
        } catch (JRException ex) {

        }
    }//GEN-LAST:event_MantSalonActionPerformed

    private void servEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_servEventoActionPerformed
        // TODO add your handling code here:
        InputStream reporte = this.getClass().getResourceAsStream("/Reportes/Servicios_eventos.jasper");
        JasperPrint jasperPrint;

        Conexion con = new Conexion();
        Connection Conn = con.conectar();

        try {
            jasperPrint = JasperFillManager.fillReport(reporte, null, Conn);
            JasperViewer jv = new JasperViewer(jasperPrint, false);
            jv.setTitle("");
            jv.setVisible(true);
        } catch (JRException ex) {

        }
    }//GEN-LAST:event_servEventoActionPerformed

    private void ventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ventasActionPerformed
        // TODO add your handling code here:
        InputStream reporte = this.getClass().getResourceAsStream("/Reportes/ventas.jasper");
        JasperPrint jasperPrint;

        Conexion con = new Conexion();
        Connection Conn = con.conectar();

        try {
            jasperPrint = JasperFillManager.fillReport(reporte, null, Conn);
            JasperViewer jv = new JasperViewer(jasperPrint, false);
            jv.setTitle("");
            jv.setVisible(true);
        } catch (JRException ex) {

        }
    }//GEN-LAST:event_ventasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    //Mis Variables
    private final CardLayout cl;
    private final IconFontUtil iconFont;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem EvtxCliente;
    private javax.swing.JMenuItem MantSalon;
    private javax.swing.JButton btnEventos;
    private javax.swing.JButton btnMant;
    private javax.swing.JButton btnServicios;
    private javax.swing.JButton btnTablas;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JMenuItem factCliente;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mReportes;
    private javax.swing.JPanel panelCards;
    private javax.swing.JPanel panelNevegacion;
    private javax.swing.JMenuItem servEvento;
    private javax.swing.JPanel statusBar;
    private javax.swing.JMenuItem ventas;
    // End of variables declaration//GEN-END:variables
}
