package Modelo.POJO;
// Generated 14-ago-2019 19:09:39 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * EventoServicio generated by hbm2java
 */
public class EventoServicio  implements java.io.Serializable {


     private EventoServicioId id;
     private Evento evento;
     private Servicio servicio;
     private Float precio;
     private Date fechaRegistro;

    public EventoServicio() {
    }

	
    public EventoServicio(EventoServicioId id, Evento evento, Servicio servicio) {
        this.id = id;
        this.evento = evento;
        this.servicio = servicio;
    }
    public EventoServicio(EventoServicioId id, Evento evento, Servicio servicio, Float precio, Date fechaRegistro) {
       this.id = id;
       this.evento = evento;
       this.servicio = servicio;
       this.precio = precio;
       this.fechaRegistro = fechaRegistro;
    }
   
    public EventoServicioId getId() {
        return this.id;
    }
    
    public void setId(EventoServicioId id) {
        this.id = id;
    }
    public Evento getEvento() {
        return this.evento;
    }
    
    public void setEvento(Evento evento) {
        this.evento = evento;
    }
    public Servicio getServicio() {
        return this.servicio;
    }
    
    public void setServicio(Servicio servicio) {
        this.servicio = servicio;
    }
    public Float getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Float precio) {
        this.precio = precio;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }




}


