package Modelo.POJO;
// Generated 14-ago-2019 19:09:39 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Mantenimiento generated by hbm2java
 */
public class Mantenimiento  implements java.io.Serializable {


     private int idMantenimiento;
     private Empresa empresa;
     private Salon salon;
     private Supervisor supervisor;
     private String tipoMantenimiento;
     private Float costo;
     private Date fechaRegistro;

    public Mantenimiento() {
    }

	
    public Mantenimiento(int idMantenimiento, Empresa empresa, Salon salon, Supervisor supervisor) {
        this.idMantenimiento = idMantenimiento;
        this.empresa = empresa;
        this.salon = salon;
        this.supervisor = supervisor;
    }
    public Mantenimiento(int idMantenimiento, Empresa empresa, Salon salon, Supervisor supervisor, String tipoMantenimiento, Float costo, Date fechaRegistro) {
       this.idMantenimiento = idMantenimiento;
       this.empresa = empresa;
       this.salon = salon;
       this.supervisor = supervisor;
       this.tipoMantenimiento = tipoMantenimiento;
       this.costo = costo;
       this.fechaRegistro = fechaRegistro;
    }
   
    public int getIdMantenimiento() {
        return this.idMantenimiento;
    }
    
    public void setIdMantenimiento(int idMantenimiento) {
        this.idMantenimiento = idMantenimiento;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public Salon getSalon() {
        return this.salon;
    }
    
    public void setSalon(Salon salon) {
        this.salon = salon;
    }
    public Supervisor getSupervisor() {
        return this.supervisor;
    }
    
    public void setSupervisor(Supervisor supervisor) {
        this.supervisor = supervisor;
    }
    public String getTipoMantenimiento() {
        return this.tipoMantenimiento;
    }
    
    public void setTipoMantenimiento(String tipoMantenimiento) {
        this.tipoMantenimiento = tipoMantenimiento;
    }
    public Float getCosto() {
        return this.costo;
    }
    
    public void setCosto(Float costo) {
        this.costo = costo;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }




}


