package Modelo.POJO;
// Generated 14-ago-2019 19:09:39 by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idUsuario;
     private String nombreUsario;
     private String rol;
     private String contrasena;

    public Usuario() {
    }

    public Usuario(String nombreUsario, String rol, String contrasena) {
       this.nombreUsario = nombreUsario;
       this.rol = rol;
       this.contrasena = contrasena;
    }
   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getNombreUsario() {
        return this.nombreUsario;
    }
    
    public void setNombreUsario(String nombreUsario) {
        this.nombreUsario = nombreUsario;
    }
    public String getRol() {
        return this.rol;
    }
    
    public void setRol(String rol) {
        this.rol = rol;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }




}


