package Modelo.POJO;
// Generated 14-ago-2019 19:09:39 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * VentaBoleto generated by hbm2java
 */
public class VentaBoleto  implements java.io.Serializable {


     private int idVentaBoleto;
     private Evento evento;
     private Date fecha;
     private Integer cantidadBoletos;
     private String cedula;

    public VentaBoleto() {
    }

	
    public VentaBoleto(int idVentaBoleto, Evento evento) {
        this.idVentaBoleto = idVentaBoleto;
        this.evento = evento;
    }
    public VentaBoleto(int idVentaBoleto, Evento evento, Date fecha, Integer cantidadBoletos, String cedula) {
       this.idVentaBoleto = idVentaBoleto;
       this.evento = evento;
       this.fecha = fecha;
       this.cantidadBoletos = cantidadBoletos;
       this.cedula = cedula;
    }
   
    public int getIdVentaBoleto() {
        return this.idVentaBoleto;
    }
    
    public void setIdVentaBoleto(int idVentaBoleto) {
        this.idVentaBoleto = idVentaBoleto;
    }
    public Evento getEvento() {
        return this.evento;
    }
    
    public void setEvento(Evento evento) {
        this.evento = evento;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Integer getCantidadBoletos() {
        return this.cantidadBoletos;
    }
    
    public void setCantidadBoletos(Integer cantidadBoletos) {
        this.cantidadBoletos = cantidadBoletos;
    }

    public String getCedula() {
        return cedula;
    }

    public void setCedula(String cedula) {
        this.cedula = cedula;
    }




}


